/******************************************************************************/
//
// This file was generated by OSAcfg_Tool utility.
// Do not modify it to prevent data loss on next editing.
//
// PROJECT NAME: OSA_908_2
//
// PLATFORM:     Microchip C30
//
/******************************************************************************/


#ifndef _OSACFG_H
#define _OSACFG_H

//------------------------------------------------------------------------------
// SYSTEM
//------------------------------------------------------------------------------

#define OS_TASKS                16   // Number of tasks that can be active at one time
#define OS_DISABLE_PRIORITY         // old style constant
#define OS_PRIORITY_LEVEL  OS_PRIORITY_DISABLED 

//------------------------------------------------------------------------------
// ENABLE CONSTANTS
//------------------------------------------------------------------------------

#define OS_ENABLE_TTIMERS           // Enable task timers (OS_Delay and OS_xxx_Wait_TO)


//------------------------------------------------------------------------------
// TYPES
//------------------------------------------------------------------------------

#define OS_TTIMER_SIZE          2   // Size of task timers (1, 2 or 4)




#endif
